
language: ruby
cache: bundler

rvm:
  - ruby
  - 2.4.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - 1.0@kul.asia
    on_failure: change
    on_success: never


sudo: false

before_install: gem install bundler -v 1.16.1
